.github/workflows/ci-cd.yml
=> Fix syntax in build workflow yml file

.github/workflows/ci-cd.yml
=> Fix pre-publish build in ci-cd.yml workflow

package.json
=> Skip git commit and tag when publishing to NPM

.github/workflows/ci-cd.yml
=> Only publish when pushing on master of theia-ide/tsp-typescript-client

yarn.lock
=> Update yarn.lock to bump minimist 0.0.8 to 1.2.5 for security fix

src/models/query/query-helper.ts
Signed-off-by: Patrick Tasse <patrick.tasse@gmail.com>
=> Align table query parameters with Trace Server Protocol

package.json
=> Add src directory when publishing to npm

src/protocol/tsp-client.ts
Signed-off-by: Arnaud Fiorini <fiorini.arnaud@gmail.com>
=> Change fetchTimeGraphArrows to return an array of TimeGraphArrow

src/models/markerset.ts, src/protocol/tsp-client.ts
Add fetchMarkerSets(expUUID).
Add markerSetId parameter to fetchAnnotationCategories().
=> Add support for marker sets

src/protocol/rest-client.ts
Signed-off-by: Marco Miller <marco.miller@ericsson.com>
=> RestClient: Fix minor use{d} verb tense typo(s)

tsp-typescript-client/src/protocol/rest-client.test.ts, tsp-typescript-client/src/protocol/rest-client.ts
I accidentally made a mistake when touching one of the functions in a previous PR.
Fix the query string creation and add tests for it.
=> fix query string creation

tsp-typescript-client/src/protocol/rest-client.ts
Clients can add a connection status listener to the RestClient to be
notified when the connection goes up or down. The connection status is
detected based on whether any HTTP request can be completed or not.
When a listener is added it will immediately receive the current status
through the listener interface.
Change-Id: I5f7fcbf4b94380b2ea349755a400bd61bbadc7d2
=> Add ConnectionStatusListener to RestClient

.github/workflows/ci-cd.yml
=> Update publish GitHub action to work with eclipse-cdt-cloud

tsp-typescript-client/src/models/xy.ts
1. XY: Add the series OutputElementStyle to the model
2. XY: Remove the unused commonXAxis from the model
Each commit message should have their necessary details.
=> XY: Add the series OutputElementStyle to the model

.vscode/launch.json
=> Add launch.json to debug test cases

.github/workflows/ci-cd.yml
=> Upgrade to node 16.x for GitHub CI

.github/workflows/ci-cd.yml
=> Upgrade to node 16.x for GitHub CI (publish)

tsp-typescript-client/fixtures/tsp-client/fetch-data-tree-0.json, tsp-typescript-client/src/models/data-tree.ts, tsp-typescript-client/src/protocol/tsp-client.test.ts, tsp-typescript-client/src/protocol/tsp-client.ts
=> Data tree endpoint

.github/workflows/ci-cd.yml, .github/workflows/license-check-workflow.yml, README.md
=> update to node 18

RELEASE, lerna.json, tsp-typescript-client/package.json
Try again for our first automated `latest` publish, after fixing a bit of missing infra
=> Release v0.4.1 (Patch)

.github/workflows/release.yml, lerna.json
Also got rid of the useless "lerna" line in `lerna.json`
=> [ci] prevent triggering release-related jobs on forks

tsp-typescript-client/package.json, yarn.lock
To pick updated version of this repo's dependencies.
=> Perform yarn upgrade

RELEASE, lerna.json, tsp-typescript-client/package.json
New patch release with updated dependencies
=> Release v0.4.3 (Patch)

tsp-typescript-client/fixtures/tsp-client/fetch-configuration-sources-0.json, tsp-typescript-client/src/models/configuration-source.ts, tsp-typescript-client/src/protocol/tsp-client.test.ts
https://json-schema.org/
see also https://github.com/eclipse-cdt-cloud/trace-server-protocol/pull/103
=> Add support for json-schema to configuration types

RELEASE, lerna.json, tsp-typescript-client/package.json
=> Release v0.5.0 (Minor)

RELEASE, lerna.json, tsp-typescript-client/package.json
=> Release v0.5.1 (Patch)

RELEASE, lerna.json, tsp-typescript-client/package.json
Mintor release v0.6.0. No code changes.
Successful CI run.
None
=> Release v0.6.0 (Minor)

RELEASE, lerna.json, tsp-typescript-client/package.json
Release v0.7.0 (Minor)
Check that CI passes.
N/A
=> Release v0.7.0 (Minor)

package.json, tsp-typescript-client/package.json, yarn.lock
Minimal update to get rid of this critical severity vulnerability.
see:
https://github.com/dependency-insights/npm/form-data/4.0.0/security?query=org%3Aeclipse-cdt-cloud
Confirm that CI passes. Optionally perform a "yarn why form-data" and confirm that the version pulled is not vulnerable. The version expected with this PR is:
`form-data@4.0.4`
N/A
=> Update dependencies to get rid of form-data vulnerability
