eclipse-cdt-cloud/tsp-typescript-client

src/models/entry.ts, src/models/query/query-helper.ts, src/models/styles.ts, src/models/table.ts, src/models/timegraph.ts, src/models/xy.ts, src/protocol/tsp-client.ts, tsconfig.json
Fixes #3
Signed-off-by: Geneviève Bastien <gbastien+lttng@versatic.net>
=> Align client classes with the TSP specification

src/models/annotation.ts, src/protocol/tsp-client.ts
Signed-off-by: Patrick Tasse <patrick.tasse@gmail.com>
=> Add annotation model and tsp-client API for fetching annotations

src/protocol/rest-client.ts, src/protocol/tsp-client-response.ts
When a TSP request response is received with an unsuccessful status code
and without a json object model, the parsing of the body as json was
throwing an error and the status code was unavailable to the caller.
Create the TspClientResponse with the plain text of the response, and
make the model optional. Make the plain text available to the caller. Do
not throw an error when the json object is absent.
Signed-off-by: Patrick Tasse <patrick.tasse@gmail.com>
=> Support unsuccessful request responses

src/models/health.ts, src/protocol/tsp-client.ts
Add the checkHealth method to request server's health status
Signed-off-by: Geneviève Bastien <gbastien@versatic.net>
=> Implement the health check service of the TSP

package.json
`yarn` or `npm` run `prepare` script when installing directly from github.
Signed-off-by: Quoc-Hao Tran <quoc-hao.tran@polymtl.ca>
=> Add prepare script for installing directly from github

README.md, jest.config.json, package.json, src/models/query/query-helper.test.ts, src/protocol/__mocks__/rest-client.ts, src/protocol/tsp-client.test.ts, yarn.lock
Added Jest using `ts-jest` and `@types/jest` packages.
Added a few tests to tsp-client and to query-helper classes.
As tsp-client makes asynchronous API calls, added a `__mock__` folder
that Jest uses to test the calls without connecting to the real backend.
To perform the tests, first install the new packages:
```
yarn add
```
Then perform the tests:
```
yarn test --verbose
```
Signed-off-by: Rodrigo Pinto <rodrigo.pinto@calian.ca>.
=> Start adding tests to project

jest.config.json
This change is the result of using the Format command(s) in VS Code.
Signed-off-by: Marco Miller <marco.miller@ericsson.com>
=> jest.config.json: Apply default VS Code formatting

.gitignore, README.md, src/models/query/query-helper.test.ts, src/protocol/__mocks__/rest-client.ts, src/protocol/rest-client.ts, src/protocol/tsp-client.test.ts
Add more tests to `tps-client.test.ts`.
This commit increases test coverage in these specific ways:
- query-helper.ts:	  from 23% to 75%;
- tsp-client.ts:	  from 8% to 35%;
- tsp-client-response.ts: maintains 56%.
Total coverage:		  from 29% to 55%.
Signed-off-by: Rodrigo Pinto <rodrigo.pinto@calian.ca>
=> Expanding unit tests

src/models/annotation.ts, src/models/bookmark.ts, src/models/experiment.ts, src/models/filter.ts, src/models/output-descriptor.ts, src/models/query/query-helper.test.ts, src/models/query/query-helper.ts, src/models/timegraph.ts, src/models/trace.ts, src/protocol/__mocks__/rest-client.ts, src/protocol/rest-client.ts, src/protocol/tsp-client-response.ts, src/protocol/tsp-client.test.ts
Fields that are known to be timestamps or durations are serialized and
deserialized as strings.
This is done to avoid loss of precision in JavaScript 'number' type for
values above Number.MAX_SAFE_INTEGER (2^53 - 1).
The models are updated to use 'bigint' type instead of 'number' for
these fields.
In outgoing requests, bigint values are replaced by strings in the
JSON.stringify() replacer. The strings are then replaced by unquoted
numbers in the JSON request.
In incoming JSON responses, long numbers are replaced by strings prior
to parsing, and the JSON.parse() reviver will replace those strings by
either bigint or number values, depending on the field. For bigint
fields, small numbers are replaced by their bigint value.
=> Serialize and deserialize timestamps as strings

tsp-typescript-client/src/models/query/query-helper.test.ts, tsp-typescript-client/src/models/query/query-helper.ts
When the requested number of samples is larger than the requested time
range, a smaller array is returned that has every time in the range from
start to end, without duplicates.
Change-Id: Ibfb109ee1df9d9aea0c1eec2e53d38904998e821
=> Avoid duplicates in requestedTimes array

package.json, tslint.json, tsp-typescript-client/package.json
What happend is that the PR that introduced the dependency was done
before a refactoring that moved the `tsp-typescript-client` package in a
different folder. But the change to the root `package.json` dependencies
didn't cause a merge conflict, so it stayed this way even though it
meant that the `tsp-typescript-client` would be published without the
new dependency.
Move the dependency from the root of the monorepo to the
`tsp-typescript-client` package.
Signed-off-by: Paul Marechal <paul.marechal@ericsson.com>
=> depend on json-bigint from the right package

tsp-typescript-client/src/protocol/rest-client.ts, tsp-typescript-client/src/protocol/test-utils.ts, tsp-typescript-client/src/protocol/tsp-client.test.ts
Catch errors thrown from the HTTP request and return a 503 response.
Catch errors thrown from JSON parser and normalizer and return a
response without model.
Change-Id: I75d6a8019254b6db1c07a91e67a6e8eb438ba57d
=> Catch errors in RestClient

README.md, tsp-typescript-client/README.md
The repository has been moved to the Eclipse cdt-cloud project and is
now located under the eclipse-cdt-cloud GitHub organization.
=> Replace theia-ide with eclipse-cdt-cloud references

tsp-typescript-client/fixtures/tsp-client/fetch-timegraph-tree-0.json, tsp-typescript-client/src/models/entry.ts, tsp-typescript-client/src/models/timegraph.ts, tsp-typescript-client/src/protocol/tsp-client.test.ts
This PR adds support for metadata in the timegraph deserializer. It includes also unit tests to verify this change.
Signed-off-by: Rodrigo Pinto <rodrigo.pinto@calian.ca>
=> Add metadata to timegraph deserializer

package.json
Update with the most up-to-date url the
package.json files in the project.
Probably was forgotten when migrating the
project to eclipse-cdt-cloud in github.
Signed-off-by: Francesco Robino <francesco.robino@ericsson.com>
=> Update package.json to cdt-cloud url/homepage

tsp-typescript-client/src/models/xy.ts, tsp-typescript-client/src/protocol/tsp-client.ts
Corresponding: TSP specitication: https://github.com/eclipse-cdt-cloud/trace-server-protocol/pull/85
Contributes to https://github.com/eclipse-cdt-cloud/theia-trace-extension/issues/786
=> Add XyEntry API to deserialize XY entry the specific attribute isDefault

.github/workflows/ci-cd.yml, lerna.json
- [lerna] option verifyAccess to false
This will permit publishing to npm using an automation token.
https://github.com/lerna/lerna/issues/2788#issuecomment-776726711
- Use actions/setup-node@v3 instead of actions/setup-node@v1
- Update to Ubuntu 20.04 in ci-cd builds
=> Fix publish to NPM

package.json
This is to make sure -next versions sort properly so 'yarn upgrade' upgrades to valid newer versions.
fixes #78
=> releng: Include date in version string for next versions

tsp-typescript-client/src/index.ts, tsp-typescript-client/src/protocol/http-tsp-client.ts, tsp-typescript-client/src/protocol/tsp-client.test.ts, tsp-typescript-client/src/protocol/tsp-client.ts
The `TspClient` is now an interface that can be used for other implementations. The existing functionality was moved to the `DefaultTspClient`. This means adopters now need to initialize the `DefaultTspClient` type instead of `TspClient` to get the default behavior. However this makes the package more flexible as different implementations can be provided, e.g. a proxy client in a Theia frontend.
Part of https://github.com/eclipse-cdt-cloud/theia-trace-extension/issues/976
Contributed on behalf of STMicroelectronics
Note: Once this is merged i can update [this PR](https://github.com/eclipse-cdt-cloud/theia-trace-extension/pull/990) to consume the changes.
=> Make TspClient reuseable interface

tsp-typescript-client/fixtures/tsp-client/configuration-0.json, tsp-typescript-client/fixtures/tsp-client/fetch-configuration-sources-0.json, tsp-typescript-client/fixtures/tsp-client/fetch-configurations-0.json, tsp-typescript-client/src/models/configuration-source.ts, tsp-typescript-client/src/models/configuration.ts, tsp-typescript-client/src/protocol/http-tsp-client.ts, tsp-typescript-client/src/protocol/tsp-client.test.ts, tsp-typescript-client/src/protocol/tsp-client.ts
This adds APIs to the tsp-client to use the end-points newly defined in TSP:
- https://github.com/eclipse-cdt-cloud/trace-server-protocol/pull/93
- https://github.com/eclipse-cdt-cloud/trace-server-protocol/pull/92
=> Add support for configuration service end-points

tsp-typescript-client/fixtures/tsp-client/fetch-configuration-sources-0.json, tsp-typescript-client/src/models/configuration-source.ts, tsp-typescript-client/src/protocol/tsp-client.test.ts
This commit changes the name of the configuration parameter property of the configuration source type model so that it matches the model returned by the trace server and as declared in the TSP specifications.
=> Update model for configuration source type parameters

tsp-typescript-client/package.json
rimraf is used as a development dependency but was pulled as a production dependency. This had the side-effect of making its own production dependencies mandatory for other projects using it.
=> Move rimraf dependency from prod to dev

.github/workflows/ci-cd.yml, .github/workflows/release.yml, README.md, RELEASE, package.json, tsp-typescript-client/README.md, tsp-typescript-client/package.json, yarn.lock
Add necessary CI infrastructure for automated publishing of latest `tsp-typescript-client` package. Also, in preparation to using said infrastructure, make small improvements in package's `package.json` and `README`.
Note: at this time, job `GitHub release` is expected to fail.
=> [CI] publish infrastructure for "latest"

.github/workflows/ci-cd.yml
This was missed in the previous infrastructure PR, and is necessary for the "publish-latest" job to run.
=> [ci] Add missing workflow trigger: 'release'

tsp-typescript-client/fixtures/tsp-client/fetch-identifier-0.json, tsp-typescript-client/src/models/identifier.ts, tsp-typescript-client/src/protocol/http-tsp-client.ts, tsp-typescript-client/src/protocol/tsp-client.test.ts, tsp-typescript-client/src/protocol/tsp-client.ts
This PR adds support for the identifier service: https://github.com/eclipse-tracecompass-incubator/org.eclipse.tracecompass.incubator/pull/17
Signed-off-by: Vlad Arama <vlad.arama@ericsson.com>
=> Implement Identifier Service

tsp-typescript-client/fixtures/tsp-client/experiment-outputs-0.json, tsp-typescript-client/fixtures/tsp-client/output-configuration-0.json, tsp-typescript-client/src/models/configuration.ts, tsp-typescript-client/src/models/output-descriptor.ts, tsp-typescript-client/src/models/query/query-helper.test.ts, tsp-typescript-client/src/models/query/query-helper.ts, tsp-typescript-client/src/models/query/query.ts, tsp-typescript-client/src/protocol/http-tsp-client.ts, tsp-typescript-client/src/protocol/tsp-client.test.ts, tsp-typescript-client/src/protocol/tsp-client.ts
- Support parentId and creation configuration in output descriptors
- Add ProviderType enum for the type in OutputDescriptors
- Add APIs to support configurable output (data provider)
- Add ConfigurationQuery and OutputConfigurationQuery
- Add utility methods in query-helper.ts to create such query instances
- Add configuration service per output (data provider)
This addition enables clients to create derived data providers from
an existing data provider.
- Add unit tests
=> Add custom analysis related APIs

tsp-typescript-client/fixtures/tsp-client/create-experiment-0.json, tsp-typescript-client/fixtures/tsp-client/delete-experiment-0.json, tsp-typescript-client/fixtures/tsp-client/delete-trace-0.json, tsp-typescript-client/fixtures/tsp-client/open-trace-0.json, tsp-typescript-client/src/models/trace.ts, tsp-typescript-client/src/protocol/tsp-client.test.ts
Add the parameter "properties" introduced by commit 499408e3979cab403a5d58 in the server (incubator).
Link to the PR for the commit: https://github.com/eclipse-tracecompass-incubator/org.eclipse.tracecompass.incubator/pull/79
=> Add parameter "properties" in model "Trace"

tsp-typescript-client/src/models/query/query.ts
In the OutputConfigurationQuery the configuration source type id was called typeId and it creates a Configuration object where the same field is called sourceTypeId for the same field. When serializing the Configuration in the derived DataProviderDescriptor over TSP the field is called sourceTypeId and this is not consistent. The returned Configuration should have the exact field names that are used when creating the data provider and the respective configuration.
The Configuration is already API while OutputConfigurationQuery is not, and it's better to change the name there.
=> Align OutputConfigurationQuery/Configuration for sourceTypeId

package.json, yarn.lock
Lerna 7.x seems to be a dead branch, so we need to use 8.x to get e.g. security updates. The upgrade looks to be seamless.
=> Upgrade to lerna 8.x, perform yarn upgrade

tsp-typescript-client/fixtures/tsp-client/experiment-outputs-0.json, tsp-typescript-client/src/models/output-capabilities.ts, tsp-typescript-client/src/models/output-descriptor.ts, tsp-typescript-client/src/protocol/tsp-client.test.ts
OutputCapabilities indicate capabilities of an output, such as "canCreate" and "canDelete". "canCreate" indicates that a given output can create a derived outputs. "canDelete" indicates that a given output can be deleted.
See also ADR: https://github.com/eclipse-cdt-cloud/theia-trace-extension/pull/1158
Run the unit tests (`yarn tests`)
N/A
=> Add optional OutputCapabilities to the output descriptor

tsp-typescript-client/src/utils/jsonbig-utils.test.ts, tsp-typescript-client/src/utils/jsonbig-utils.ts
Add utility to support json stringify/parse with JSONBigInt.
Example Usages:
```javascript
// Usage with normalizer
import { Experiment } from 'tsp-typescript-client/lib/models/experiment';
let input = JSONBigUtils.stringify(experiment);
let output: Experiment = JSONBigUtils.parse(input, Experiment);
// Usage no normalizer
input = JSONBigUtils.stringify(inputObj);
output = JSONBigUtils.parse<string>(input);
input = JSONBigUtils.stringify(BigInt("1234567890123456789"));
output = JSONBigUtils.parse<bigint>(bigIntInput);
```
fixes #57
Unit tests including new tests for utility successful.
N/A
=> Add utility to support json stringify/parse with JSONBigInt 

tsp-typescript-client/fixtures/tsp-client/fetch-data-tree-0.json, tsp-typescript-client/fixtures/tsp-client/fetch-timegraph-tree-0.json, tsp-typescript-client/fixtures/tsp-client/fetch-xy-tree-0.json, tsp-typescript-client/src/models/entry.ts, tsp-typescript-client/src/protocol/tsp-client.test.ts
Adds `autoExpandLevel` flag to EntryModel.
Relates to:
https://github.com/eclipse-tracecompass/org.eclipse.tracecompass/pull/277
https://github.com/eclipse-tracecompass-incubator/org.eclipse.tracecompass.incubator/pull/196
Make sure this works with latest tracecompass-server.
The functionality for the flag, the ability for the front-end to correctly expand / collapse tree nodes based on the value of `autoExpandLevel`, needs to be implemented.
- [ x] As an author, I have thoroughly tested my changes and carefully followed the instructions in this template
=> Add `autoExpandLevel` flag to EntryModel

tsp-typescript-client/src/models/error-response.ts, tsp-typescript-client/src/models/experiment-error-response.ts, tsp-typescript-client/src/models/trace-error-response.ts, tsp-typescript-client/src/protocol/rest-client.ts, tsp-typescript-client/src/protocol/tsp-client-response.ts, tsp-typescript-client/src/protocol/tsp-client.test.ts
Return the ErrorResponse message in the getStatusMessage() of TspClientResponse.
Contributes to fix issue:
https://github.com/eclipse-cdt-cloud/trace-server-protocol/issues/122
Code review and use it in a FE (e.g. vscode-trace-extension) and try an example error case, e.g. open trace with file that is not a trace.
N/A
=> Support ErrorResponse for error cases in all specified messages

tsp-typescript-client/fixtures/tsp-client/fetch-configuration-sources-0.json, tsp-typescript-client/src/models/configuration-source.ts, tsp-typescript-client/src/protocol/tsp-client.test.ts
The TSP specifies `required` instead of `isRequired`. This commit aligns the implementation with the specification.
Fix field name to 'required` of ConfigurationParameterDescriptor. The TSP specifies `required` instead of `isRequired`. This commit aligns the implementation with the specification.
See also:
https://github.com/eclipse-tracecompass-incubator/org.eclipse.tracecompass.incubator/issues/246
There is on unit test in this repo that verifies this (`configurationSourceTypes` of `tsp-client-tests.ts`) which should run successfully now.
=> Fix field name to 'required` of ConfigurationParameterDescriptor
